In [1]:
import pandas as pd
import numpy as np

# Exploring
import scipy.stats as stats

# Visualizing
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

# default pandas decimal number display format
pd.options.display.float_format = '{:20,.2f}'.format

from wrangle import new_zillow_data, get_zillow_data

In [2]:
df = get_zillow_data()
df.head().T

/Users/derekbixby/codeup-data-science/clustering_exercises/wrangle.py:38: DtypeWarning: Columns (67,69,75,77) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('zillow.csv', index_col=0)

,0,1,2,3,4
id,1727539,1387261,11677,2288172,1970746
parcelid,14297519,17052889,14186244,12177905,10887214
airconditioningtypeid,NaN,NaN,NaN,NaN,1.00
architecturalstyletypeid,NaN,NaN,NaN,NaN,NaN
basementsqft,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...
storytypeid.1,NaN,NaN,NaN,NaN,NaN
storydesc,NaN,NaN,NaN,NaN,NaN
typeconstructiontypeid.1,NaN,NaN,NaN,NaN,NaN
typeconstructiondesc,NaN,NaN,NaN,NaN,NaN
parcelid.2,14297519,17052889,14186244,12177905,10887214

In [3]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,66028,66029,66030,66031,66032,66033,66034,66035,66036,66037
id,1727539,1387261,11677,2288172,1970746,781532,870991,1246926,1585097,1639362,...,1684937,1642435,1373391,2274245,2864704,673515,2968375,1843709,1187175,2455685
parcelid,14297519,17052889,14186244,12177905,10887214,12095076,12069064,12790562,11542646,11104527,...,12666457,10858613,10722691,12412492,10833991,11000655,17239384,12773139,12826780,13083743
airconditioningtypeid,NaN,NaN,NaN,NaN,1.00,1.00,NaN,NaN,NaN,1.00,...,NaN,1.00,1.00,NaN,1.00,NaN,NaN,1.00,NaN,NaN
architecturalstyletypeid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
basementsqft,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
storytypeid.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
storydesc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
typeconstructiontypeid.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
typeconstructiondesc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
parcelid.2,14297519,17052889,14186244,12177905,10887214,12095076,12069064,12790562,11542646,11104527,...,12666457,10858613,10722691,12412492,10833991,11000655,17239384,12773139,12826780,13083743

In [5]:
df = df.drop_duplicates(subset='parcelid', keep='last')

In [10]:
df

,id,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,...,buildingclassdesc,heatingorsystemtypeid.1,heatingorsystemdesc,propertylandusetypeid.1,propertylandusedesc,storytypeid.1,storydesc,typeconstructiontypeid.1,typeconstructiondesc,parcelid.2
0,1727539,14297519,NaN,NaN,NaN,3.50,4.00,NaN,NaN,3.50,...,NaN,NaN,NaN,261,Single Family Residential,NaN,NaN,NaN,NaN,14297519
1,1387261,17052889,NaN,NaN,NaN,1.00,2.00,NaN,NaN,1.00,...,NaN,NaN,NaN,261,Single Family Residential,NaN,NaN,NaN,NaN,17052889
2,11677,14186244,NaN,NaN,NaN,2.00,3.00,NaN,NaN,2.00,...,NaN,NaN,NaN,261,Single Family Residential,NaN,NaN,NaN,NaN,14186244
3,2288172,12177905,NaN,NaN,NaN,3.00,4.00,NaN,8.00,3.00,...,NaN,2.00,Central,261,Single Family Residential,NaN,NaN,NaN,NaN,12177905
4,1970746,10887214,1.00,NaN,NaN,3.00,3.00,NaN,8.00,3.00,...,NaN,2.00,Central,266,Condominium,NaN,NaN,NaN,NaN,10887214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66033,673515,11000655,NaN,NaN,NaN,2.00,2.00,NaN,6.00,2.00,...,NaN,2.00,Central,261,Single Family Residential,NaN,NaN,NaN,NaN,11000655
66034,2968375,17239384,NaN,NaN,NaN,2.00,4.00,NaN,NaN,2.00,...,NaN,NaN,NaN,261,Single Family Residential,NaN,NaN,NaN,NaN,17239384
66035,1843709,12773139,1.00,NaN,NaN,1.00,3.00,NaN,4.00,1.00,...,NaN,2.00,Central,261,Single Family Residential,NaN,NaN,NaN,NaN,12773139
66036,1187175,12826780,NaN,NaN,NaN,2.00,3.00,NaN,6.00,2.00,...,NaN,2.00,Central,261,Single Family Residential,NaN,NaN,NaN,NaN,12826780
66037,2455685,13083743,NaN,NaN,NaN,2.00,3.00,NaN,4.00,2.00,...,NaN,7.00,Floor/Wall,261,Single Family Residential,NaN,NaN,NaN,NaN,13083743

In [11]:
df = df.dropna(subset=['longitude', 'latitude'])
df

,id,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,...,buildingclassdesc,heatingorsystemtypeid.1,heatingorsystemdesc,propertylandusetypeid.1,propertylandusedesc,storytypeid.1,storydesc,typeconstructiontypeid.1,typeconstructiondesc,parcelid.2
0,1727539,14297519,NaN,NaN,NaN,3.50,4.00,NaN,NaN,3.50,...,NaN,NaN,NaN,261,Single Family Residential,NaN,NaN,NaN,NaN,14297519
1,1387261,17052889,NaN,NaN,NaN,1.00,2.00,NaN,NaN,1.00,...,NaN,NaN,NaN,261,Single Family Residential,NaN,NaN,NaN,NaN,17052889
2,11677,14186244,NaN,NaN,NaN,2.00,3.00,NaN,NaN,2.00,...,NaN,NaN,NaN,261,Single Family Residential,NaN,NaN,NaN,NaN,14186244
3,2288172,12177905,NaN,NaN,NaN,3.00,4.00,NaN,8.00,3.00,...,NaN,2.00,Central,261,Single Family Residential,NaN,NaN,NaN,NaN,12177905
4,1970746,10887214,1.00,NaN,NaN,3.00,3.00,NaN,8.00,3.00,...,NaN,2.00,Central,266,Condominium,NaN,NaN,NaN,NaN,10887214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66033,673515,11000655,NaN,NaN,NaN,2.00,2.00,NaN,6.00,2.00,...,NaN,2.00,Central,261,Single Family Residential,NaN,NaN,NaN,NaN,11000655
66034,2968375,17239384,NaN,NaN,NaN,2.00,4.00,NaN,NaN,2.00,...,NaN,NaN,NaN,261,Single Family Residential,NaN,NaN,NaN,NaN,17239384
66035,1843709,12773139,1.00,NaN,NaN,1.00,3.00,NaN,4.00,1.00,...,NaN,2.00,Central,261,Single Family Residential,NaN,NaN,NaN,NaN,12773139
66036,1187175,12826780,NaN,NaN,NaN,2.00,3.00,NaN,6.00,2.00,...,NaN,2.00,Central,261,Single Family Residential,NaN,NaN,NaN,NaN,12826780
66037,2455685,13083743,NaN,NaN,NaN,2.00,3.00,NaN,4.00,2.00,...,NaN,7.00,Floor/Wall,261,Single Family Residential,NaN,NaN,NaN,NaN,13083743

In [17]:
def handle_missing_values(df, prop_required_column = .5, prop_required_row = .70):
    threshold = int(round(prop_required_column*len(df.index),0))
    df.dropna(axis=1, thresh=threshold, inplace=True)
    threshold = int(round(prop_required_row*len(df.columns),0))
    df.dropna(axis=0, thresh=threshold, inplace=True)
    return df

In [18]:
handle_missing_values(df)

,id,parcelid,bathroomcnt,bedroomcnt,buildingqualitytypeid,calculatedbathnbr,calculatedfinishedsquarefeet,finishedsquarefeet12,fips,fullbathcnt,...,censustractandblock,id.1,parcelid.1,logerror,transactiondate,heatingorsystemtypeid.1,heatingorsystemdesc,propertylandusetypeid.1,propertylandusedesc,parcelid.2
0,1727539,14297519,3.50,4.00,NaN,3.50,"3,100.00","3,100.00","6,059.00",3.00,...,"60,590,630,072,012.00",0,14297519,0.03,2017-01-01,NaN,NaN,261,Single Family Residential,14297519
1,1387261,17052889,1.00,2.00,NaN,1.00,"1,465.00","1,465.00","6,111.00",1.00,...,"61,110,010,023,006.00",1,17052889,0.06,2017-01-01,NaN,NaN,261,Single Family Residential,17052889
2,11677,14186244,2.00,3.00,NaN,2.00,"1,243.00","1,243.00","6,059.00",2.00,...,"60,590,218,022,012.00",2,14186244,0.01,2017-01-01,NaN,NaN,261,Single Family Residential,14186244
3,2288172,12177905,3.00,4.00,8.00,3.00,"2,376.00","2,376.00","6,037.00",3.00,...,"60,373,001,001,006.00",3,12177905,-0.10,2017-01-01,2.00,Central,261,Single Family Residential,12177905
4,1970746,10887214,3.00,3.00,8.00,3.00,"1,312.00","1,312.00","6,037.00",3.00,...,"60,371,236,012,000.00",4,10887214,0.01,2017-01-01,2.00,Central,266,Condominium,10887214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66033,673515,11000655,2.00,2.00,6.00,2.00,"1,286.00","1,286.00","6,037.00",2.00,...,"60,371,014,003,002.00",77609,11000655,0.02,2017-09-20,2.00,Central,261,Single Family Residential,11000655
66034,2968375,17239384,2.00,4.00,NaN,2.00,"1,612.00","1,612.00","6,111.00",2.00,...,"61,110,084,022,016.00",77610,17239384,0.01,2017-09-21,NaN,NaN,261,Single Family Residential,17239384
66035,1843709,12773139,1.00,3.00,4.00,1.00,"1,032.00","1,032.00","6,037.00",1.00,...,"60,374,338,022,005.00",77611,12773139,0.04,2017-09-21,2.00,Central,261,Single Family Residential,12773139
66036,1187175,12826780,2.00,3.00,6.00,2.00,"1,762.00","1,762.00","6,037.00",2.00,...,"60,375,034,021,020.00",77612,12826780,0.01,2017-09-25,2.00,Central,261,Single Family Residential,12826780
66037,2455685,13083743,2.00,3.00,4.00,2.00,"1,050.00","1,050.00","6,037.00",2.00,...,"60,374,081,401,000.00",77613,13083743,-0.20,2018-05-25,7.00,Floor/Wall,261,Single Family Residential,13083743